/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AuthenticatedUserRouteImport } from './routes/_authenticated/_user'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthThirdPartyRouteImport } from './routes/_auth/third-party'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthenticatedInstructorRouteRouteImport } from './routes/_authenticated/instructor/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedInstructorRevenueRouteImport } from './routes/_authenticated/instructor/revenue'
import { Route as AuthenticatedInstructorNotificationRouteImport } from './routes/_authenticated/instructor/notification'
import { Route as AuthenticatedInstructorMessageRouteImport } from './routes/_authenticated/instructor/message'
import { Route as AuthenticatedInstructorDashboardRouteImport } from './routes/_authenticated/instructor/dashboard'
import { Route as AuthenticatedAdminUserManagementRouteImport } from './routes/_authenticated/admin/user-management'
import { Route as AuthenticatedAdminRequestRouteImport } from './routes/_authenticated/admin/request'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminCourseRouteImport } from './routes/_authenticated/admin/course'
import { Route as AuthenticatedAdminCategoryRouteImport } from './routes/_authenticated/admin/category'
import { Route as AuthenticatedUserSettingsRouteImport } from './routes/_authenticated/_user/settings'
import { Route as AuthenticatedUserRequestTeachingRouteImport } from './routes/_authenticated/_user/request-teaching'
import { Route as AuthenticatedUserRequestRouteImport } from './routes/_authenticated/_user/request'
import { Route as AuthenticatedUserProfileRouteImport } from './routes/_authenticated/_user/profile'
import { Route as AuthenticatedUserCourseRouteImport } from './routes/_authenticated/_user/course'
import { Route as AuthenticatedInstructorLessonRouteRouteImport } from './routes/_authenticated/instructor/lesson/route'
import { Route as AuthenticatedInstructorCourseIndexRouteImport } from './routes/_authenticated/instructor/course/index'
import { Route as AuthenticatedInstructorLessonAddNewRouteImport } from './routes/_authenticated/instructor/lesson/add-new'
import { Route as AuthenticatedInstructorLessonLessonIdRouteImport } from './routes/_authenticated/instructor/lesson/$lessonId'
import { Route as AuthenticatedInstructorCourseAddNewRouteImport } from './routes/_authenticated/instructor/course/add-new'
import { Route as AuthenticatedInstructorCourseCourseIdRouteRouteImport } from './routes/_authenticated/instructor/course/$courseId/route'
import { Route as AuthenticatedInstructorCourseCourseIdIndexRouteImport } from './routes/_authenticated/instructor/course/$courseId/index'
import { Route as AuthenticatedInstructorCourseCourseIdStudentRouteImport } from './routes/_authenticated/instructor/course/$courseId/student'
import { Route as AuthenticatedInstructorCourseCourseIdSettingsRouteImport } from './routes/_authenticated/instructor/course/$courseId/settings'
import { Route as AuthenticatedInstructorCourseCourseIdReviewRouteImport } from './routes/_authenticated/instructor/course/$courseId/review'
import { Route as AuthenticatedInstructorCourseCourseIdDetailRouteImport } from './routes/_authenticated/instructor/course/$courseId/detail'
import { Route as AuthenticatedInstructorCourseCourseIdChapterRouteImport } from './routes/_authenticated/instructor/course/$courseId/chapter'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedUserRoute = AuthenticatedUserRouteImport.update({
  id: '/_user',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthThirdPartyRoute = AuthThirdPartyRouteImport.update({
  id: '/third-party',
  path: '/third-party',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedInstructorRouteRoute =
  AuthenticatedInstructorRouteRouteImport.update({
    id: '/instructor',
    path: '/instructor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstructorRevenueRoute =
  AuthenticatedInstructorRevenueRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => AuthenticatedInstructorRouteRoute,
  } as any)
const AuthenticatedInstructorNotificationRoute =
  AuthenticatedInstructorNotificationRouteImport.update({
    id: '/notification',
    path: '/notification',
    getParentRoute: () => AuthenticatedInstructorRouteRoute,
  } as any)
const AuthenticatedInstructorMessageRoute =
  AuthenticatedInstructorMessageRouteImport.update({
    id: '/message',
    path: '/message',
    getParentRoute: () => AuthenticatedInstructorRouteRoute,
  } as any)
const AuthenticatedInstructorDashboardRoute =
  AuthenticatedInstructorDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedInstructorRouteRoute,
  } as any)
const AuthenticatedAdminUserManagementRoute =
  AuthenticatedAdminUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRequestRoute =
  AuthenticatedAdminRequestRouteImport.update({
    id: '/request',
    path: '/request',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCourseRoute =
  AuthenticatedAdminCourseRouteImport.update({
    id: '/course',
    path: '/course',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoryRoute =
  AuthenticatedAdminCategoryRouteImport.update({
    id: '/category',
    path: '/category',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedUserSettingsRoute =
  AuthenticatedUserSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedUserRoute,
  } as any)
const AuthenticatedUserRequestTeachingRoute =
  AuthenticatedUserRequestTeachingRouteImport.update({
    id: '/request-teaching',
    path: '/request-teaching',
    getParentRoute: () => AuthenticatedUserRoute,
  } as any)
const AuthenticatedUserRequestRoute =
  AuthenticatedUserRequestRouteImport.update({
    id: '/request',
    path: '/request',
    getParentRoute: () => AuthenticatedUserRoute,
  } as any)
const AuthenticatedUserProfileRoute =
  AuthenticatedUserProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedUserRoute,
  } as any)
const AuthenticatedUserCourseRoute = AuthenticatedUserCourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => AuthenticatedUserRoute,
} as any)
const AuthenticatedInstructorLessonRouteRoute =
  AuthenticatedInstructorLessonRouteRouteImport.update({
    id: '/lesson',
    path: '/lesson',
    getParentRoute: () => AuthenticatedInstructorRouteRoute,
  } as any)
const AuthenticatedInstructorCourseIndexRoute =
  AuthenticatedInstructorCourseIndexRouteImport.update({
    id: '/course/',
    path: '/course/',
    getParentRoute: () => AuthenticatedInstructorRouteRoute,
  } as any)
const AuthenticatedInstructorLessonAddNewRoute =
  AuthenticatedInstructorLessonAddNewRouteImport.update({
    id: '/add-new',
    path: '/add-new',
    getParentRoute: () => AuthenticatedInstructorLessonRouteRoute,
  } as any)
const AuthenticatedInstructorLessonLessonIdRoute =
  AuthenticatedInstructorLessonLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => AuthenticatedInstructorLessonRouteRoute,
  } as any)
const AuthenticatedInstructorCourseAddNewRoute =
  AuthenticatedInstructorCourseAddNewRouteImport.update({
    id: '/course/add-new',
    path: '/course/add-new',
    getParentRoute: () => AuthenticatedInstructorRouteRoute,
  } as any)
const AuthenticatedInstructorCourseCourseIdRouteRoute =
  AuthenticatedInstructorCourseCourseIdRouteRouteImport.update({
    id: '/course/$courseId',
    path: '/course/$courseId',
    getParentRoute: () => AuthenticatedInstructorRouteRoute,
  } as any)
const AuthenticatedInstructorCourseCourseIdIndexRoute =
  AuthenticatedInstructorCourseCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInstructorCourseCourseIdRouteRoute,
  } as any)
const AuthenticatedInstructorCourseCourseIdStudentRoute =
  AuthenticatedInstructorCourseCourseIdStudentRouteImport.update({
    id: '/student',
    path: '/student',
    getParentRoute: () => AuthenticatedInstructorCourseCourseIdRouteRoute,
  } as any)
const AuthenticatedInstructorCourseCourseIdSettingsRoute =
  AuthenticatedInstructorCourseCourseIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedInstructorCourseCourseIdRouteRoute,
  } as any)
const AuthenticatedInstructorCourseCourseIdReviewRoute =
  AuthenticatedInstructorCourseCourseIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedInstructorCourseCourseIdRouteRoute,
  } as any)
const AuthenticatedInstructorCourseCourseIdDetailRoute =
  AuthenticatedInstructorCourseCourseIdDetailRouteImport.update({
    id: '/detail',
    path: '/detail',
    getParentRoute: () => AuthenticatedInstructorCourseCourseIdRouteRoute,
  } as any)
const AuthenticatedInstructorCourseCourseIdChapterRoute =
  AuthenticatedInstructorCourseCourseIdChapterRouteImport.update({
    id: '/chapter',
    path: '/chapter',
    getParentRoute: () => AuthenticatedInstructorCourseCourseIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/instructor': typeof AuthenticatedInstructorRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/third-party': typeof AuthThirdPartyRoute
  '/verify': typeof AuthVerifyRoute
  '/about': typeof PublicAboutRoute
  '/': typeof PublicIndexRoute
  '/instructor/lesson': typeof AuthenticatedInstructorLessonRouteRouteWithChildren
  '/course': typeof AuthenticatedUserCourseRoute
  '/profile': typeof AuthenticatedUserProfileRoute
  '/request': typeof AuthenticatedUserRequestRoute
  '/request-teaching': typeof AuthenticatedUserRequestTeachingRoute
  '/settings': typeof AuthenticatedUserSettingsRoute
  '/admin/category': typeof AuthenticatedAdminCategoryRoute
  '/admin/course': typeof AuthenticatedAdminCourseRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/request': typeof AuthenticatedAdminRequestRoute
  '/admin/user-management': typeof AuthenticatedAdminUserManagementRoute
  '/instructor/dashboard': typeof AuthenticatedInstructorDashboardRoute
  '/instructor/message': typeof AuthenticatedInstructorMessageRoute
  '/instructor/notification': typeof AuthenticatedInstructorNotificationRoute
  '/instructor/revenue': typeof AuthenticatedInstructorRevenueRoute
  '/instructor/course/$courseId': typeof AuthenticatedInstructorCourseCourseIdRouteRouteWithChildren
  '/instructor/course/add-new': typeof AuthenticatedInstructorCourseAddNewRoute
  '/instructor/lesson/$lessonId': typeof AuthenticatedInstructorLessonLessonIdRoute
  '/instructor/lesson/add-new': typeof AuthenticatedInstructorLessonAddNewRoute
  '/instructor/course': typeof AuthenticatedInstructorCourseIndexRoute
  '/instructor/course/$courseId/chapter': typeof AuthenticatedInstructorCourseCourseIdChapterRoute
  '/instructor/course/$courseId/detail': typeof AuthenticatedInstructorCourseCourseIdDetailRoute
  '/instructor/course/$courseId/review': typeof AuthenticatedInstructorCourseCourseIdReviewRoute
  '/instructor/course/$courseId/settings': typeof AuthenticatedInstructorCourseCourseIdSettingsRoute
  '/instructor/course/$courseId/student': typeof AuthenticatedInstructorCourseCourseIdStudentRoute
  '/instructor/course/$courseId/': typeof AuthenticatedInstructorCourseCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/instructor': typeof AuthenticatedInstructorRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/third-party': typeof AuthThirdPartyRoute
  '/verify': typeof AuthVerifyRoute
  '/about': typeof PublicAboutRoute
  '/': typeof PublicIndexRoute
  '/instructor/lesson': typeof AuthenticatedInstructorLessonRouteRouteWithChildren
  '/course': typeof AuthenticatedUserCourseRoute
  '/profile': typeof AuthenticatedUserProfileRoute
  '/request': typeof AuthenticatedUserRequestRoute
  '/request-teaching': typeof AuthenticatedUserRequestTeachingRoute
  '/settings': typeof AuthenticatedUserSettingsRoute
  '/admin/category': typeof AuthenticatedAdminCategoryRoute
  '/admin/course': typeof AuthenticatedAdminCourseRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/request': typeof AuthenticatedAdminRequestRoute
  '/admin/user-management': typeof AuthenticatedAdminUserManagementRoute
  '/instructor/dashboard': typeof AuthenticatedInstructorDashboardRoute
  '/instructor/message': typeof AuthenticatedInstructorMessageRoute
  '/instructor/notification': typeof AuthenticatedInstructorNotificationRoute
  '/instructor/revenue': typeof AuthenticatedInstructorRevenueRoute
  '/instructor/course/add-new': typeof AuthenticatedInstructorCourseAddNewRoute
  '/instructor/lesson/$lessonId': typeof AuthenticatedInstructorLessonLessonIdRoute
  '/instructor/lesson/add-new': typeof AuthenticatedInstructorLessonAddNewRoute
  '/instructor/course': typeof AuthenticatedInstructorCourseIndexRoute
  '/instructor/course/$courseId/chapter': typeof AuthenticatedInstructorCourseCourseIdChapterRoute
  '/instructor/course/$courseId/detail': typeof AuthenticatedInstructorCourseCourseIdDetailRoute
  '/instructor/course/$courseId/review': typeof AuthenticatedInstructorCourseCourseIdReviewRoute
  '/instructor/course/$courseId/settings': typeof AuthenticatedInstructorCourseCourseIdSettingsRoute
  '/instructor/course/$courseId/student': typeof AuthenticatedInstructorCourseCourseIdStudentRoute
  '/instructor/course/$courseId': typeof AuthenticatedInstructorCourseCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/instructor': typeof AuthenticatedInstructorRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/third-party': typeof AuthThirdPartyRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_authenticated/_user': typeof AuthenticatedUserRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/instructor/lesson': typeof AuthenticatedInstructorLessonRouteRouteWithChildren
  '/_authenticated/_user/course': typeof AuthenticatedUserCourseRoute
  '/_authenticated/_user/profile': typeof AuthenticatedUserProfileRoute
  '/_authenticated/_user/request': typeof AuthenticatedUserRequestRoute
  '/_authenticated/_user/request-teaching': typeof AuthenticatedUserRequestTeachingRoute
  '/_authenticated/_user/settings': typeof AuthenticatedUserSettingsRoute
  '/_authenticated/admin/category': typeof AuthenticatedAdminCategoryRoute
  '/_authenticated/admin/course': typeof AuthenticatedAdminCourseRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/request': typeof AuthenticatedAdminRequestRoute
  '/_authenticated/admin/user-management': typeof AuthenticatedAdminUserManagementRoute
  '/_authenticated/instructor/dashboard': typeof AuthenticatedInstructorDashboardRoute
  '/_authenticated/instructor/message': typeof AuthenticatedInstructorMessageRoute
  '/_authenticated/instructor/notification': typeof AuthenticatedInstructorNotificationRoute
  '/_authenticated/instructor/revenue': typeof AuthenticatedInstructorRevenueRoute
  '/_authenticated/instructor/course/$courseId': typeof AuthenticatedInstructorCourseCourseIdRouteRouteWithChildren
  '/_authenticated/instructor/course/add-new': typeof AuthenticatedInstructorCourseAddNewRoute
  '/_authenticated/instructor/lesson/$lessonId': typeof AuthenticatedInstructorLessonLessonIdRoute
  '/_authenticated/instructor/lesson/add-new': typeof AuthenticatedInstructorLessonAddNewRoute
  '/_authenticated/instructor/course/': typeof AuthenticatedInstructorCourseIndexRoute
  '/_authenticated/instructor/course/$courseId/chapter': typeof AuthenticatedInstructorCourseCourseIdChapterRoute
  '/_authenticated/instructor/course/$courseId/detail': typeof AuthenticatedInstructorCourseCourseIdDetailRoute
  '/_authenticated/instructor/course/$courseId/review': typeof AuthenticatedInstructorCourseCourseIdReviewRoute
  '/_authenticated/instructor/course/$courseId/settings': typeof AuthenticatedInstructorCourseCourseIdSettingsRoute
  '/_authenticated/instructor/course/$courseId/student': typeof AuthenticatedInstructorCourseCourseIdStudentRoute
  '/_authenticated/instructor/course/$courseId/': typeof AuthenticatedInstructorCourseCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/instructor'
    | '/sign-in'
    | '/sign-up'
    | '/third-party'
    | '/verify'
    | '/about'
    | '/'
    | '/instructor/lesson'
    | '/course'
    | '/profile'
    | '/request'
    | '/request-teaching'
    | '/settings'
    | '/admin/category'
    | '/admin/course'
    | '/admin/dashboard'
    | '/admin/request'
    | '/admin/user-management'
    | '/instructor/dashboard'
    | '/instructor/message'
    | '/instructor/notification'
    | '/instructor/revenue'
    | '/instructor/course/$courseId'
    | '/instructor/course/add-new'
    | '/instructor/lesson/$lessonId'
    | '/instructor/lesson/add-new'
    | '/instructor/course'
    | '/instructor/course/$courseId/chapter'
    | '/instructor/course/$courseId/detail'
    | '/instructor/course/$courseId/review'
    | '/instructor/course/$courseId/settings'
    | '/instructor/course/$courseId/student'
    | '/instructor/course/$courseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/instructor'
    | '/sign-in'
    | '/sign-up'
    | '/third-party'
    | '/verify'
    | '/about'
    | '/'
    | '/instructor/lesson'
    | '/course'
    | '/profile'
    | '/request'
    | '/request-teaching'
    | '/settings'
    | '/admin/category'
    | '/admin/course'
    | '/admin/dashboard'
    | '/admin/request'
    | '/admin/user-management'
    | '/instructor/dashboard'
    | '/instructor/message'
    | '/instructor/notification'
    | '/instructor/revenue'
    | '/instructor/course/add-new'
    | '/instructor/lesson/$lessonId'
    | '/instructor/lesson/add-new'
    | '/instructor/course'
    | '/instructor/course/$courseId/chapter'
    | '/instructor/course/$courseId/detail'
    | '/instructor/course/$courseId/review'
    | '/instructor/course/$courseId/settings'
    | '/instructor/course/$courseId/student'
    | '/instructor/course/$courseId'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/admin'
    | '/_authenticated/instructor'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/third-party'
    | '/_auth/verify'
    | '/_authenticated/_user'
    | '/_public/about'
    | '/_public/'
    | '/_authenticated/instructor/lesson'
    | '/_authenticated/_user/course'
    | '/_authenticated/_user/profile'
    | '/_authenticated/_user/request'
    | '/_authenticated/_user/request-teaching'
    | '/_authenticated/_user/settings'
    | '/_authenticated/admin/category'
    | '/_authenticated/admin/course'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/request'
    | '/_authenticated/admin/user-management'
    | '/_authenticated/instructor/dashboard'
    | '/_authenticated/instructor/message'
    | '/_authenticated/instructor/notification'
    | '/_authenticated/instructor/revenue'
    | '/_authenticated/instructor/course/$courseId'
    | '/_authenticated/instructor/course/add-new'
    | '/_authenticated/instructor/lesson/$lessonId'
    | '/_authenticated/instructor/lesson/add-new'
    | '/_authenticated/instructor/course/'
    | '/_authenticated/instructor/course/$courseId/chapter'
    | '/_authenticated/instructor/course/$courseId/detail'
    | '/_authenticated/instructor/course/$courseId/review'
    | '/_authenticated/instructor/course/$courseId/settings'
    | '/_authenticated/instructor/course/$courseId/student'
    | '/_authenticated/instructor/course/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/_user': {
      id: '/_authenticated/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedUserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/third-party': {
      id: '/_auth/third-party'
      path: '/third-party'
      fullPath: '/third-party'
      preLoaderRoute: typeof AuthThirdPartyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/instructor': {
      id: '/_authenticated/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof AuthenticatedInstructorRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instructor/revenue': {
      id: '/_authenticated/instructor/revenue'
      path: '/revenue'
      fullPath: '/instructor/revenue'
      preLoaderRoute: typeof AuthenticatedInstructorRevenueRouteImport
      parentRoute: typeof AuthenticatedInstructorRouteRoute
    }
    '/_authenticated/instructor/notification': {
      id: '/_authenticated/instructor/notification'
      path: '/notification'
      fullPath: '/instructor/notification'
      preLoaderRoute: typeof AuthenticatedInstructorNotificationRouteImport
      parentRoute: typeof AuthenticatedInstructorRouteRoute
    }
    '/_authenticated/instructor/message': {
      id: '/_authenticated/instructor/message'
      path: '/message'
      fullPath: '/instructor/message'
      preLoaderRoute: typeof AuthenticatedInstructorMessageRouteImport
      parentRoute: typeof AuthenticatedInstructorRouteRoute
    }
    '/_authenticated/instructor/dashboard': {
      id: '/_authenticated/instructor/dashboard'
      path: '/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof AuthenticatedInstructorDashboardRouteImport
      parentRoute: typeof AuthenticatedInstructorRouteRoute
    }
    '/_authenticated/admin/user-management': {
      id: '/_authenticated/admin/user-management'
      path: '/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AuthenticatedAdminUserManagementRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/request': {
      id: '/_authenticated/admin/request'
      path: '/request'
      fullPath: '/admin/request'
      preLoaderRoute: typeof AuthenticatedAdminRequestRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/course': {
      id: '/_authenticated/admin/course'
      path: '/course'
      fullPath: '/admin/course'
      preLoaderRoute: typeof AuthenticatedAdminCourseRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/category': {
      id: '/_authenticated/admin/category'
      path: '/category'
      fullPath: '/admin/category'
      preLoaderRoute: typeof AuthenticatedAdminCategoryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_user/settings': {
      id: '/_authenticated/_user/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedUserSettingsRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/_user/request-teaching': {
      id: '/_authenticated/_user/request-teaching'
      path: '/request-teaching'
      fullPath: '/request-teaching'
      preLoaderRoute: typeof AuthenticatedUserRequestTeachingRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/_user/request': {
      id: '/_authenticated/_user/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof AuthenticatedUserRequestRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/_user/profile': {
      id: '/_authenticated/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedUserProfileRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/_user/course': {
      id: '/_authenticated/_user/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof AuthenticatedUserCourseRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/instructor/lesson': {
      id: '/_authenticated/instructor/lesson'
      path: '/lesson'
      fullPath: '/instructor/lesson'
      preLoaderRoute: typeof AuthenticatedInstructorLessonRouteRouteImport
      parentRoute: typeof AuthenticatedInstructorRouteRoute
    }
    '/_authenticated/instructor/course/': {
      id: '/_authenticated/instructor/course/'
      path: '/course'
      fullPath: '/instructor/course'
      preLoaderRoute: typeof AuthenticatedInstructorCourseIndexRouteImport
      parentRoute: typeof AuthenticatedInstructorRouteRoute
    }
    '/_authenticated/instructor/lesson/add-new': {
      id: '/_authenticated/instructor/lesson/add-new'
      path: '/add-new'
      fullPath: '/instructor/lesson/add-new'
      preLoaderRoute: typeof AuthenticatedInstructorLessonAddNewRouteImport
      parentRoute: typeof AuthenticatedInstructorLessonRouteRoute
    }
    '/_authenticated/instructor/lesson/$lessonId': {
      id: '/_authenticated/instructor/lesson/$lessonId'
      path: '/$lessonId'
      fullPath: '/instructor/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedInstructorLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedInstructorLessonRouteRoute
    }
    '/_authenticated/instructor/course/add-new': {
      id: '/_authenticated/instructor/course/add-new'
      path: '/course/add-new'
      fullPath: '/instructor/course/add-new'
      preLoaderRoute: typeof AuthenticatedInstructorCourseAddNewRouteImport
      parentRoute: typeof AuthenticatedInstructorRouteRoute
    }
    '/_authenticated/instructor/course/$courseId': {
      id: '/_authenticated/instructor/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/instructor/course/$courseId'
      preLoaderRoute: typeof AuthenticatedInstructorCourseCourseIdRouteRouteImport
      parentRoute: typeof AuthenticatedInstructorRouteRoute
    }
    '/_authenticated/instructor/course/$courseId/': {
      id: '/_authenticated/instructor/course/$courseId/'
      path: '/'
      fullPath: '/instructor/course/$courseId/'
      preLoaderRoute: typeof AuthenticatedInstructorCourseCourseIdIndexRouteImport
      parentRoute: typeof AuthenticatedInstructorCourseCourseIdRouteRoute
    }
    '/_authenticated/instructor/course/$courseId/student': {
      id: '/_authenticated/instructor/course/$courseId/student'
      path: '/student'
      fullPath: '/instructor/course/$courseId/student'
      preLoaderRoute: typeof AuthenticatedInstructorCourseCourseIdStudentRouteImport
      parentRoute: typeof AuthenticatedInstructorCourseCourseIdRouteRoute
    }
    '/_authenticated/instructor/course/$courseId/settings': {
      id: '/_authenticated/instructor/course/$courseId/settings'
      path: '/settings'
      fullPath: '/instructor/course/$courseId/settings'
      preLoaderRoute: typeof AuthenticatedInstructorCourseCourseIdSettingsRouteImport
      parentRoute: typeof AuthenticatedInstructorCourseCourseIdRouteRoute
    }
    '/_authenticated/instructor/course/$courseId/review': {
      id: '/_authenticated/instructor/course/$courseId/review'
      path: '/review'
      fullPath: '/instructor/course/$courseId/review'
      preLoaderRoute: typeof AuthenticatedInstructorCourseCourseIdReviewRouteImport
      parentRoute: typeof AuthenticatedInstructorCourseCourseIdRouteRoute
    }
    '/_authenticated/instructor/course/$courseId/detail': {
      id: '/_authenticated/instructor/course/$courseId/detail'
      path: '/detail'
      fullPath: '/instructor/course/$courseId/detail'
      preLoaderRoute: typeof AuthenticatedInstructorCourseCourseIdDetailRouteImport
      parentRoute: typeof AuthenticatedInstructorCourseCourseIdRouteRoute
    }
    '/_authenticated/instructor/course/$courseId/chapter': {
      id: '/_authenticated/instructor/course/$courseId/chapter'
      path: '/chapter'
      fullPath: '/instructor/course/$courseId/chapter'
      preLoaderRoute: typeof AuthenticatedInstructorCourseCourseIdChapterRouteImport
      parentRoute: typeof AuthenticatedInstructorCourseCourseIdRouteRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthThirdPartyRoute: typeof AuthThirdPartyRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthThirdPartyRoute: AuthThirdPartyRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCategoryRoute: typeof AuthenticatedAdminCategoryRoute
  AuthenticatedAdminCourseRoute: typeof AuthenticatedAdminCourseRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminRequestRoute: typeof AuthenticatedAdminRequestRoute
  AuthenticatedAdminUserManagementRoute: typeof AuthenticatedAdminUserManagementRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCategoryRoute: AuthenticatedAdminCategoryRoute,
    AuthenticatedAdminCourseRoute: AuthenticatedAdminCourseRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminRequestRoute: AuthenticatedAdminRequestRoute,
    AuthenticatedAdminUserManagementRoute:
      AuthenticatedAdminUserManagementRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedInstructorLessonRouteRouteChildren {
  AuthenticatedInstructorLessonLessonIdRoute: typeof AuthenticatedInstructorLessonLessonIdRoute
  AuthenticatedInstructorLessonAddNewRoute: typeof AuthenticatedInstructorLessonAddNewRoute
}

const AuthenticatedInstructorLessonRouteRouteChildren: AuthenticatedInstructorLessonRouteRouteChildren =
  {
    AuthenticatedInstructorLessonLessonIdRoute:
      AuthenticatedInstructorLessonLessonIdRoute,
    AuthenticatedInstructorLessonAddNewRoute:
      AuthenticatedInstructorLessonAddNewRoute,
  }

const AuthenticatedInstructorLessonRouteRouteWithChildren =
  AuthenticatedInstructorLessonRouteRoute._addFileChildren(
    AuthenticatedInstructorLessonRouteRouteChildren,
  )

interface AuthenticatedInstructorCourseCourseIdRouteRouteChildren {
  AuthenticatedInstructorCourseCourseIdChapterRoute: typeof AuthenticatedInstructorCourseCourseIdChapterRoute
  AuthenticatedInstructorCourseCourseIdDetailRoute: typeof AuthenticatedInstructorCourseCourseIdDetailRoute
  AuthenticatedInstructorCourseCourseIdReviewRoute: typeof AuthenticatedInstructorCourseCourseIdReviewRoute
  AuthenticatedInstructorCourseCourseIdSettingsRoute: typeof AuthenticatedInstructorCourseCourseIdSettingsRoute
  AuthenticatedInstructorCourseCourseIdStudentRoute: typeof AuthenticatedInstructorCourseCourseIdStudentRoute
  AuthenticatedInstructorCourseCourseIdIndexRoute: typeof AuthenticatedInstructorCourseCourseIdIndexRoute
}

const AuthenticatedInstructorCourseCourseIdRouteRouteChildren: AuthenticatedInstructorCourseCourseIdRouteRouteChildren =
  {
    AuthenticatedInstructorCourseCourseIdChapterRoute:
      AuthenticatedInstructorCourseCourseIdChapterRoute,
    AuthenticatedInstructorCourseCourseIdDetailRoute:
      AuthenticatedInstructorCourseCourseIdDetailRoute,
    AuthenticatedInstructorCourseCourseIdReviewRoute:
      AuthenticatedInstructorCourseCourseIdReviewRoute,
    AuthenticatedInstructorCourseCourseIdSettingsRoute:
      AuthenticatedInstructorCourseCourseIdSettingsRoute,
    AuthenticatedInstructorCourseCourseIdStudentRoute:
      AuthenticatedInstructorCourseCourseIdStudentRoute,
    AuthenticatedInstructorCourseCourseIdIndexRoute:
      AuthenticatedInstructorCourseCourseIdIndexRoute,
  }

const AuthenticatedInstructorCourseCourseIdRouteRouteWithChildren =
  AuthenticatedInstructorCourseCourseIdRouteRoute._addFileChildren(
    AuthenticatedInstructorCourseCourseIdRouteRouteChildren,
  )

interface AuthenticatedInstructorRouteRouteChildren {
  AuthenticatedInstructorLessonRouteRoute: typeof AuthenticatedInstructorLessonRouteRouteWithChildren
  AuthenticatedInstructorDashboardRoute: typeof AuthenticatedInstructorDashboardRoute
  AuthenticatedInstructorMessageRoute: typeof AuthenticatedInstructorMessageRoute
  AuthenticatedInstructorNotificationRoute: typeof AuthenticatedInstructorNotificationRoute
  AuthenticatedInstructorRevenueRoute: typeof AuthenticatedInstructorRevenueRoute
  AuthenticatedInstructorCourseCourseIdRouteRoute: typeof AuthenticatedInstructorCourseCourseIdRouteRouteWithChildren
  AuthenticatedInstructorCourseAddNewRoute: typeof AuthenticatedInstructorCourseAddNewRoute
  AuthenticatedInstructorCourseIndexRoute: typeof AuthenticatedInstructorCourseIndexRoute
}

const AuthenticatedInstructorRouteRouteChildren: AuthenticatedInstructorRouteRouteChildren =
  {
    AuthenticatedInstructorLessonRouteRoute:
      AuthenticatedInstructorLessonRouteRouteWithChildren,
    AuthenticatedInstructorDashboardRoute:
      AuthenticatedInstructorDashboardRoute,
    AuthenticatedInstructorMessageRoute: AuthenticatedInstructorMessageRoute,
    AuthenticatedInstructorNotificationRoute:
      AuthenticatedInstructorNotificationRoute,
    AuthenticatedInstructorRevenueRoute: AuthenticatedInstructorRevenueRoute,
    AuthenticatedInstructorCourseCourseIdRouteRoute:
      AuthenticatedInstructorCourseCourseIdRouteRouteWithChildren,
    AuthenticatedInstructorCourseAddNewRoute:
      AuthenticatedInstructorCourseAddNewRoute,
    AuthenticatedInstructorCourseIndexRoute:
      AuthenticatedInstructorCourseIndexRoute,
  }

const AuthenticatedInstructorRouteRouteWithChildren =
  AuthenticatedInstructorRouteRoute._addFileChildren(
    AuthenticatedInstructorRouteRouteChildren,
  )

interface AuthenticatedUserRouteChildren {
  AuthenticatedUserCourseRoute: typeof AuthenticatedUserCourseRoute
  AuthenticatedUserProfileRoute: typeof AuthenticatedUserProfileRoute
  AuthenticatedUserRequestRoute: typeof AuthenticatedUserRequestRoute
  AuthenticatedUserRequestTeachingRoute: typeof AuthenticatedUserRequestTeachingRoute
  AuthenticatedUserSettingsRoute: typeof AuthenticatedUserSettingsRoute
}

const AuthenticatedUserRouteChildren: AuthenticatedUserRouteChildren = {
  AuthenticatedUserCourseRoute: AuthenticatedUserCourseRoute,
  AuthenticatedUserProfileRoute: AuthenticatedUserProfileRoute,
  AuthenticatedUserRequestRoute: AuthenticatedUserRequestRoute,
  AuthenticatedUserRequestTeachingRoute: AuthenticatedUserRequestTeachingRoute,
  AuthenticatedUserSettingsRoute: AuthenticatedUserSettingsRoute,
}

const AuthenticatedUserRouteWithChildren =
  AuthenticatedUserRoute._addFileChildren(AuthenticatedUserRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedInstructorRouteRoute: typeof AuthenticatedInstructorRouteRouteWithChildren
  AuthenticatedUserRoute: typeof AuthenticatedUserRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedInstructorRouteRoute:
    AuthenticatedInstructorRouteRouteWithChildren,
  AuthenticatedUserRoute: AuthenticatedUserRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
